# Generated by Django 2.1.7 on 2019-03-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0009_auto_20190317_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='email',
            new_name='email_restaurante',
        ),
    ]
