# Generated by Django 2.1.7 on 2019-03-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0010_auto_20190317_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='WIFI',
            new_name='wifi',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='mesa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
