# Generated by Django 2.1.7 on 2019-03-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0012_auto_20190325_0132'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table=None,
        ),
    ]
