# Generated by Django 2.1.7 on 2019-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0013_auto_20190325_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.IntegerField(null=True),
        ),
    ]
