# Generated by Django 2.1.7 on 2019-03-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0020_auto_20190329_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='foto',
        ),
    ]
