# Generated by Django 2.1.7 on 2019-03-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0021_remove_menu_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tipo',
        ),
    ]
