# Generated by Django 2.1.7 on 2019-04-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0022_remove_menu_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AddField(
            model_name='menu',
            name='campo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
