# Generated by Django 2.1.7 on 2019-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0028_auto_20190422_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='menu',
            field=models.ManyToManyField(to='listado.menu'),
        ),
    ]
