# Generated by Django 2.1.7 on 2019-04-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0032_reservamenu_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservamenu',
            old_name='persona',
            new_name='personas',
        ),
    ]
