# Generated by Django 2.1.7 on 2019-04-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0033_auto_20190427_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamenu',
            name='campo',
            field=models.BooleanField(default=False),
        ),
    ]
