# Generated by Django 2.1.7 on 2019-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0038_auto_20190503_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
