# Generated by Django 2.1.7 on 2019-05-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0044_auto_20190503_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservamenu',
            old_name='personas',
            new_name='repeticion',
        ),
    ]
