# Generated by Django 2.1.7 on 2019-05-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0046_reservamenu_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservamenu',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
