# Generated by Django 2.1.7 on 2019-03-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0005_auto_20190313_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
