# Generated by Django 2.1.7 on 2019-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0006_auto_20190314_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='restaurante',
            field=models.IntegerField(default=1),
        ),
    ]
