# Generated by Django 2.1.7 on 2019-03-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0007_reserva_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listado.restaurante'),
        ),
    ]
