# Generated by Django 2.1.7 on 2019-03-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0011_auto_20190325_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='estacionamiento',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='fumar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='tarjetas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='wifi',
            field=models.BooleanField(),
        ),
    ]
