# Generated by Django 2.1.7 on 2019-03-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0014_reserva_mesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario',
            new_name='User',
        ),
    ]
