# Generated by Django 2.1.7 on 2019-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0016_auto_20190327_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='tipoComida',
            field=models.CharField(choices=[('Vegana', 'Vegana'), ('Pastas', 'Pastas'), ('Parrilla', 'Parrilla')], max_length=100),
        ),
    ]
