# Generated by Django 2.1.7 on 2019-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0019_auto_20190329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
