# Generated by Django 2.1.7 on 2019-04-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0023_auto_20190401_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='campo',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='Menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listado.menu'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
