# Generated by Django 2.1.7 on 2019-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0026_auto_20190409_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
    ]
