# Generated by Django 2.1.7 on 2019-04-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0027_auto_20190409_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='campo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=True),
        ),
    ]
