# Generated by Django 2.1.7 on 2019-04-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0034_reservamenu_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='campo',
        ),
    ]
