# Generated by Django 2.1.7 on 2019-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0035_remove_menu_campo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='mesa',
            new_name='mesas_total',
        ),
        migrations.RemoveField(
            model_name='reservamenu',
            name='User',
        ),
        migrations.AlterField(
            model_name='reservamenu',
            name='personas',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
