# Generated by Django 2.1.7 on 2019-05-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0039_auto_20190503_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
