# Generated by Django 2.1.7 on 2019-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0042_auto_20190503_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dia_hora',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
