# Generated by Django 2.1.7 on 2019-05-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0043_auto_20190503_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='dia_hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
