# Generated by Django 2.1.7 on 2019-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0045_auto_20190503_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamenu',
            name='precio',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
