# Generated by Django 2.1.7 on 2019-03-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario_id',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
